models:
  v5_5_ru:
    language: ru
    warmup: true
    hash_prefix: 50081637b602126ee06cb3bc8a744d25651d2da149ee8864b9a379bfdd934437
  v3_en:
    language: en
locales:
  ru_RU:
    voices:
      aidar:
        model: v5_5_ru
        gender: male
      eugene:
        model: v5_5_ru
        gender: male
      baya:
        model: v5_5_ru
        gender: female
      kseniya:
        model: v5_5_ru
        gender: female
      xenia:
        model: v5_5_ru
        gender: female
  en_US:
    voices:
      henry:
        speaker: en_2
        model: v3_en
        gender: male
      sophia:
        speaker: en_3
        model: v3_en
        gender: female
