models:
  v5_5_ru:
    sample_rate:
    - 8000
    - 24000
    - 48000
  v5_cis_base:
    sample_rate:
    - 8000
    - 24000
    - 48000
  v5_cis_base_nostress:
    sample_rate:
    - 8000
    - 24000
    - 48000
  v3_en:
    sample_rate:
    - 8000
    - 24000
    - 48000
locales:
- ru_RU
- en_US
voices:
  silero-v5_5_ru-aidar:
    speaker: "aidar"
    model: "v5_5_ru"
    locale: "ru_RU"
    language: "ru"
    gender: "male"
  silero-v5_5_ru-eugene:
    speaker: "eugene"
    model: "v5_5_ru"
    locale: "ru_RU"
    language: "ru"
    gender: "male"
  silero-v5_5_ru-baya:
    speaker: "baya"
    model: "v5_5_ru"
    locale: "ru_RU"
    language: "ru"
    gender: "female"
  silero-v5_5_ru-kseniya:
    speaker: "kseniya"
    model: "v5_5_ru"
    locale: "ru_RU"
    language: "ru"
    gender: "female"
  silero-v5_5_ru-xenia:
    speaker: "xenia"
    model: "v5_5_ru"
    locale: "ru_RU"
    language: "ru"
    gender: "female"
  silero-v3_en-en_0:
    speaker: "en_0"
    model: "v3_en"
    locale: "en_US"
    language: "en"
    gender: "male"
  silero-v5_cis_base-aigul:
    speaker: "aigul"
    model: "v5_cis_base"
    locale: "ru_RU"
    language: "ru"
    gender: "female"
  silero-v5_cis_base-albina:
    speaker: "albina"
    model: "v5_cis_base"
    locale: "ru_RU"
    language: "ru"
    gender: "female"
  silero-v5_cis_base-alexandr:
    speaker: "alexandr"
    model: "v5_cis_base"
    locale: "ru_RU"
    language: "ru"
    gender: "male"
  silero-v5_cis_base-alfia:
    speaker: "alfia"
    model: "v5_cis_base"
    locale: "ru_RU"
    language: "ru"
    gender: "female"
  silero-v5_cis_base-alfia2:
    speaker: "alfia2"
    model: "v5_cis_base"
    locale: "ru_RU"
    language: "ru"
    gender: "female"
  silero-v5_cis_base-bogdan:
    speaker: "bogdan"
    model: "v5_cis_base"
    locale: "ru_RU"
    language: "ru"
    gender: "male"
  silero-v5_cis_base-dmitriy:
    speaker: "dmitriy"
    model: "v5_cis_base"
    locale: "ru_RU"
    language: "ru"
    gender: "male"
  silero-v5_cis_base-eduard:
    speaker: "eduard"
    model: "v5_cis_base"
    locale: "ru_RU"
    language: "ru"
    gender: "male"
  silero-v5_cis_base-ekaterina:
    speaker: "ekaterina"
    model: "v5_cis_base"
    locale: "ru_RU"
    language: "ru"
    gender: "female"
  silero-v5_cis_base-gamat:
    speaker: "gamat"
    model: "v5_cis_base"
    locale: "ru_RU"
    language: "ru"
    gender: "male"
  silero-v5_cis_base-igor:
    speaker: "igor"
    model: "v5_cis_base"
    locale: "ru_RU"
    language: "ru"
    gender: "male"
  silero-v5_cis_base-karina:
    speaker: "karina"
    model: "v5_cis_base"
    locale: "ru_RU"
    language: "ru"
    gender: "female"
  silero-v5_cis_base-kejilgan:
    speaker: "kejilgan"
    model: "v5_cis_base"
    locale: "ru_RU"
    language: "ru"
    gender: "female"
  silero-v5_cis_base-kermen:
    speaker: "kermen"
    model: "v5_cis_base"
    locale: "ru_RU"
    language: "ru"
    gender: "male"
  silero-v5_cis_base-marat:
    speaker: "marat"
    model: "v5_cis_base"
    locale: "ru_RU"
    language: "ru"
    gender: "male"
  silero-v5_cis_base-miyau:
    speaker: "miyau"
    model: "v5_cis_base"
    locale: "ru_RU"
    language: "ru"
    gender: "male"
  silero-v5_cis_base-nurgul:
    speaker: "nurgul"
    model: "v5_cis_base"
    locale: "ru_RU"
    language: "ru"
    gender: "female"
  silero-v5_cis_base-oksana:
    speaker: "oksana"
    model: "v5_cis_base"
    locale: "ru_RU"
    language: "ru"
    gender: "female"
  silero-v5_cis_base-onaoy:
    speaker: "onaoy"
    model: "v5_cis_base"
    locale: "ru_RU"
    language: "ru"
    gender: "female"
  silero-v5_cis_base-ramilia:
    speaker: "ramilia"
    model: "v5_cis_base"
    locale: "ru_RU"
    language: "ru"
    gender: "female"
  silero-v5_cis_base-roman:
    speaker: "roman"
    model: "v5_cis_base"
    locale: "ru_RU"
    language: "ru"
    gender: "male"
  silero-v5_cis_base-safarhuja:
    speaker: "safarhuja"
    model: "v5_cis_base"
    locale: "ru_RU"
    language: "ru"
    gender: "male"
  silero-v5_cis_base-saida:
    speaker: "saida"
    model: "v5_cis_base"
    locale: "ru_RU"
    language: "ru"
    gender: "female"
  silero-v5_cis_base-sibday:
    speaker: "sibday"
    model: "v5_cis_base"
    locale: "ru_RU"
    language: "ru"
    gender: "male"
  silero-v5_cis_base-vika:
    speaker: "vika"
    model: "v5_cis_base"
    locale: "ru_RU"
    language: "ru"
    gender: "female"
  silero-v5_cis_base-zara:
    speaker: "zara"
    model: "v5_cis_base"
    locale: "ru_RU"
    language: "ru"
    gender: "female"
  silero-v5_cis_base-zhadyra:
    speaker: "zhadyra"
    model: "v5_cis_base"
    locale: "ru_RU"
    language: "ru"
    gender: "female"
  silero-v5_cis_base-zhazira:
    speaker: "zhazira"
    model: "v5_cis_base"
    locale: "ru_RU"
    language: "ru"
    gender: "female"
  silero-v5_cis_base-zinaida:
    speaker: "zinaida"
    model: "v5_cis_base"
    locale: "ru_RU"
    language: "ru"
    gender: "female"
  silero-v5_cis_base_nostress-aigul:
    speaker: "aigul"
    model: "v5_cis_base_nostress"
    locale: "ru_RU"
    language: "ru"
    gender: "female"
  silero-v5_cis_base_nostress-albina:
    speaker: "albina"
    model: "v5_cis_base_nostress"
    locale: "ru_RU"
    language: "ru"
    gender: "female"
  silero-v5_cis_base_nostress-alexandr:
    speaker: "alexandr"
    model: "v5_cis_base_nostress"
    locale: "ru_RU"
    language: "ru"
    gender: "male"
  silero-v5_cis_base_nostress-alfia:
    speaker: "alfia"
    model: "v5_cis_base_nostress"
    locale: "ru_RU"
    language: "ru"
    gender: "female"
  silero-v5_cis_base_nostress-alfia2:
    speaker: "alfia2"
    model: "v5_cis_base_nostress"
    locale: "ru_RU"
    language: "ru"
    gender: "female"
  silero-v5_cis_base_nostress-bogdan:
    speaker: "bogdan"
    model: "v5_cis_base_nostress"
    locale: "ru_RU"
    language: "ru"
    gender: "male"
  silero-v5_cis_base_nostress-dmitriy:
    speaker: "dmitriy"
    model: "v5_cis_base_nostress"
    locale: "ru_RU"
    language: "ru"
    gender: "male"
  silero-v5_cis_base_nostress-eduard:
    speaker: "eduard"
    model: "v5_cis_base_nostress"
    locale: "ru_RU"
    language: "ru"
    gender: "male"
  silero-v5_cis_base_nostress-ekaterina:
    speaker: "ekaterina"
    model: "v5_cis_base_nostress"
    locale: "ru_RU"
    language: "ru"
    gender: "female"
  silero-v5_cis_base_nostress-gamat:
    speaker: "gamat"
    model: "v5_cis_base_nostress"
    locale: "ru_RU"
    language: "ru"
    gender: "male"
  silero-v5_cis_base_nostress-igor:
    speaker: "igor"
    model: "v5_cis_base_nostress"
    locale: "ru_RU"
    language: "ru"
    gender: "male"
  silero-v5_cis_base_nostress-karina:
    speaker: "karina"
    model: "v5_cis_base_nostress"
    locale: "ru_RU"
    language: "ru"
    gender: "female"
  silero-v5_cis_base_nostress-kejilgan:
    speaker: "kejilgan"
    model: "v5_cis_base_nostress"
    locale: "ru_RU"
    language: "ru"
    gender: "female"
  silero-v5_cis_base_nostress-kermen:
    speaker: "kermen"
    model: "v5_cis_base_nostress"
    locale: "ru_RU"
    language: "ru"
    gender: "male"
  silero-v5_cis_base_nostress-marat:
    speaker: "marat"
    model: "v5_cis_base_nostress"
    locale: "ru_RU"
    language: "ru"
    gender: "male"
  silero-v5_cis_base_nostress-miyau:
    speaker: "miyau"
    model: "v5_cis_base_nostress"
    locale: "ru_RU"
    language: "ru"
    gender: "male"
  silero-v5_cis_base_nostress-nurgul:
    speaker: "nurgul"
    model: "v5_cis_base_nostress"
    locale: "ru_RU"
    language: "ru"
    gender: "female"
  silero-v5_cis_base_nostress-oksana:
    speaker: "oksana"
    model: "v5_cis_base_nostress"
    locale: "ru_RU"
    language: "ru"
    gender: "female"
  silero-v5_cis_base_nostress-onaoy:
    speaker: "onaoy"
    model: "v5_cis_base_nostress"
    locale: "ru_RU"
    language: "ru"
    gender: "female"
  silero-v5_cis_base_nostress-ramilia:
    speaker: "ramilia"
    model: "v5_cis_base_nostress"
    locale: "ru_RU"
    language: "ru"
    gender: "female"
  silero-v5_cis_base_nostress-roman:
    speaker: "roman"
    model: "v5_cis_base_nostress"
    locale: "ru_RU"
    language: "ru"
    gender: "male"
  silero-v5_cis_base_nostress-safarhuja:
    speaker: "safarhuja"
    model: "v5_cis_base_nostress"
    locale: "ru_RU"
    language: "ru"
    gender: "male"
  silero-v5_cis_base_nostress-saida:
    speaker: "saida"
    model: "v5_cis_base_nostress"
    locale: "ru_RU"
    language: "ru"
    gender: "female"
  silero-v5_cis_base_nostress-sibday:
    speaker: "sibday"
    model: "v5_cis_base_nostress"
    locale: "ru_RU"
    language: "ru"
    gender: "male"
  silero-v5_cis_base_nostress-vika:
    speaker: "vika"
    model: "v5_cis_base_nostress"
    locale: "ru_RU"
    language: "ru"
    gender: "female"
  silero-v5_cis_base_nostress-zara:
    speaker: "zara"
    model: "v5_cis_base_nostress"
    locale: "ru_RU"
    language: "ru"
    gender: "female"
  silero-v5_cis_base_nostress-zhadyra:
    speaker: "zhadyra"
    model: "v5_cis_base_nostress"
    locale: "ru_RU"
    language: "ru"
    gender: "female"
  silero-v5_cis_base_nostress-zhazira:
    speaker: "zhazira"
    model: "v5_cis_base_nostress"
    locale: "ru_RU"
    language: "ru"
    gender: "female"
  silero-v5_cis_base_nostress-zinaida:
    speaker: "zinaida"
    model: "v5_cis_base_nostress"
    locale: "ru_RU"
    language: "ru"
    gender: "female"